package model.lov;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Dec 31 12:48:29 PKT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Active_StatusImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public Active_StatusImpl() {
    }
}

