package model.lov;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jan 23 13:12:18 PKT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Crop_Type_LOVImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public Crop_Type_LOVImpl() {
    }
}

