package model.lov;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 24 09:58:19 PKT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class District_Name_LOVImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public District_Name_LOVImpl() {
    }
}

