package model.lov;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 04 16:30:49 PKT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Marital_Status_LOVImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public Marital_Status_LOVImpl() {
    }
}

