package model.lov;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 28 16:10:54 PKT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Modules_Menu_Names_LOVRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        ModuleMenuId,
        ModuleMenuName;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return Modules_Menu_Names_LOVRowImpl.AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return Modules_Menu_Names_LOVRowImpl.AttributesEnum.firstIndex() + Modules_Menu_Names_LOVRowImpl.AttributesEnum
                                                                                                            .staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = Modules_Menu_Names_LOVRowImpl.AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int MODULEMENUID = AttributesEnum.ModuleMenuId.index();
    public static final int MODULEMENUNAME = AttributesEnum.ModuleMenuName.index();

    /**
     * This is the default constructor (do not remove).
     */
    public Modules_Menu_Names_LOVRowImpl() {
    }
}

