package model.lov;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 22 10:18:35 PKT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Month_lovImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public Month_lovImpl() {
    }
}

