package model.lov;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 28 11:10:08 PKT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Role_Master_Name_LOVImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public Role_Master_Name_LOVImpl() {
    }
}

