package model.lov;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jan 23 18:22:23 PKT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Trainer_Name_LOVImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public Trainer_Name_LOVImpl() {
    }
}

